spring.application.name=Pizza
spring.datasource.url= jdbc:postgresql://localhost:5432/PizzaDB
spring.datasource.username=postgres
spring.datasource.password=2729310Aa
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml
